# Generated by Django 3.1.4 on 2023-05-22 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('emergency_person', models.CharField(max_length=100)),
                ('date_of_employment', models.DateField()),
                ('date_of_resignation', models.DateField(blank=True, null=True)),
                ('affiliation_fiscal_year', models.PositiveIntegerField()),
                ('qualifications', models.TextField()),
                ('work_contents', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
